---   
 <img align="left" width="75" height="75"  src="https://upload.wikimedia.org/wikipedia/en/c/c8/University_of_the_Punjab_logo.png"> 

<h1 align="center">Tools and Techniques for Data Science</h1>
<h1 align="center">Neural Networks From Scratch in Python</h1>

---  

<h2 align="right"> Muhammad Sheraz (Data Scientist)</h2>
<h1 align="center"> Lec 1 (Coding Our First Neurons)</h1>

<div height='1000px' width='100%'>
    <img width='49%' src='Images/n1.png'>
     <img width='49%' src='Images/n2.jpg'>
</div>

## A Single Neuron

In [10]:
inputs = [ 1.0 , 2.0 , 3.0 , 2.5 ]
weights = [ 0.2 , 0.8 , - 0.5 , 1.0 ]
bias = 2.0

In [11]:
output = (inputs[ 0 ] * weights[ 0 ] +
inputs[ 1 ] * weights[ 1 ] +
inputs[ 2 ] * weights[ 2 ] +
inputs[ 3 ] * weights[ 3 ] + bias)
print (output)

4.8


## A Layer of Neurons

In [12]:
inputs = [ 1 , 2 , 3 , 2.5 ]
weights1 = [ 0.2 , 0.8 , - 0.5 , 1 ]
weights2 = [ 0.5 , - 0.91 , 0.26 , - 0.5 ]
weights3 = [ - 0.26 , - 0.27 , 0.17 , 0.87 ]
bias1 = 2
bias2 = 3
bias3 = 0.5

In [13]:
outputs = [
# Neuron 1:
inputs[ 0 ] * weights1[ 0 ] +
inputs[ 1 ] * weights1[ 1 ] +
inputs[ 2 ] * weights1[ 2 ] +
inputs[ 3 ] * weights1[ 3 ] + bias1,
# Neuron 2:
inputs[ 0 ] * weights2[ 0 ] +
inputs[ 1 ] * weights2[ 1 ] +
inputs[ 2 ] * weights2[ 2 ] +
inputs[ 3 ] * weights2[ 3 ] + bias2,
# Neuron 3:
inputs[ 0 ] * weights3[ 0 ] +
inputs[ 1 ] * weights3[ 1 ] +
inputs[ 2 ] * weights3[ 2 ] +
inputs[ 3 ] * weights3[ 3 ] + bias3]
print (outputs)

[4.8, 1.21, 2.385]


In [15]:
inputs = [ 1 , 2 , 3 , 2.5 ]
weights = [[ 0.2 , 0.8 , - 0.5 , 1 ],
[ 0.5 , - 0.91 , 0.26 , - 0.5 ],
[ - 0.26 , - 0.27 , 0.17 , 0.87 ]]
biases = [ 2 , 3 , 0.5 ]
# Output of current layer
layer_outputs = []
# For each neuron
for neuron_weights, neuron_bias in zip (weights, biases):
    # Zeroed output of given neuron
    neuron_output = 0
    # For each input and weight to the neuron
    for n_input, weight in zip (inputs, neuron_weights):
        # Multiply this input by associated weight
        # and add to the neuron’s output variable
        neuron_output += n_input * weight
    # Add bias
    neuron_output += neuron_bias
    # Put neuron’s result to the layer’s output list
    layer_outputs.append(neuron_output)
print (layer_outputs)

[4.8, 1.21, 2.385]


### Tensors, Arrays and Vectors

In [17]:
l = [ 1 , 5 , 6 , 2 ]
print('list: ',l)

lol = [[ 1 , 5 , 6 , 2 ],
[ 3 , 2 , 1 , 3 ]]

print('A list of lists: ',lol)

lolol = [[[ 1 , 5 , 6 , 2 ],
[ 3 , 2 , 1 , 3 ]],
[[ 5 , 2 , 1 , 2 ],
[ 6 , 4 , 8 , 4 ]],
[[ 2 , 8 , 5 , 3 ],
[ 1 , 1 , 9 , 4 ]]]

print('A list of lists of lists! ',lolol)

list:  [1, 5, 6, 2]
A list of lists:  [[1, 5, 6, 2], [3, 2, 1, 3]]
A list of lists of lists!  [[[1, 5, 6, 2], [3, 2, 1, 3]], [[5, 2, 1, 2], [6, 4, 8, 4]], [[2, 8, 5, 3], [1, 1, 9, 4]]]


## Dot Product and Vector Addition

In [19]:
a = [ 1 , 2 , 3 ]
b = [ 2 , 3 , 4 ]
dot_product = a[ 0 ] * b[ 0 ] + a[ 1 ] * b[ 1 ] + a[ 2 ] * b[ 2 ]
print ('Dot Product: ',dot_product)

Dot Product:  20


## A Single Neuron with NumPy

In [20]:
import numpy as np
inputs = [ 1.0 , 2.0 , 3.0 , 2.5 ]
weights = [ 0.2 , 0.8 , - 0.5 , 1.0 ]
bias = 2.0
outputs = np.dot(weights, inputs) + bias
print (outputs)

4.8


## A Layer of Neurons with NumPy

In [22]:
import numpy as np
inputs = [ 1.0 , 2.0 , 3.0 , 2.5 ]
weights = [[ 0.2 , 0.8 , - 0.5 , 1 ],
            [ 0.5 , - 0.91 , 0.26 , - 0.5 ],
            [ - 0.26 , - 0.27 , 0.17 , 0.87 ]]
biases = [ 2.0 , 3.0 , 0.5 ]
layer_outputs = np.dot(weights, inputs) + biases
print (layer_outputs)

[4.8   1.21  2.385]


## Matrix Product

In [3]:
import numpy as np

# Define two matrices
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
result_matrix = np.dot(matrix_a, matrix_b)

# Display the result
print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

print("\nResult Matrix:")
print(result_matrix)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result Matrix:
[[ 58  64]
 [139 154]]


## Transposition for the Matrix Product

In [7]:
a = [ 1 , 2 , 3 ]
np.array([a]).T


array([[1],
       [2],
       [3]])

In [8]:
a = [ 1 , 2 , 3 ]
b = [ 2 , 3 , 4 ]
a = np.array([a])
b = np.array([b]).T
np.dot(a, b)

array([[20]])

## A Layer of Neurons & Batch of Data w/ NumPy

In [9]:
inputs = [[ 1.0 , 2.0 , 3.0 , 2.5 ],
        [ 2.0 , 5.0 , - 1.0 , 2.0 ],
        [ - 1.5 , 2.7 , 3.3 , - 0.8 ]]

weights = [[ 0.2 , 0.8 , - 0.5 , 1.0 ],
        [ 0.5 , - 0.91 , 0.26 , - 0.5 ],
        [ - 0.26 , - 0.27 , 0.17 , 0.87 ]]

biases = [ 2.0 , 3.0 , 0.5 ]

layer_outputs = np.dot(inputs, np.array(weights).T) + biases

print (layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
